### ISSUE TITLE
inference time

### ISSUE THREAD

**Issue by castiel520** [kilsen512/R3DCNN-tensorflow#4]
Hi Kilsenp,

Thanks for sharing your incredible work!
I wonder what hardware did you use to get the realtime performance, is it a Titan X as the paper mentioned? 

Thanks,
Baitao

**Comment by kilianyp** [comment]
Hi,
no, a Titan X was for inference not necessary, I used a Nvidia 1060. I am not quite sure how many forward passes I could do per second, but it was alright (I'd guess maybe 3 forward passes / second).

**Comment by castiel520** [comment]
@kilsenp thank you! i saw your demo video on youtube, it looks really good. 
btw, have you try on RGB frames to classify the gestures?

**Comment by kilianyp** [comment]
Hi,
no, I haven't tried that. I only used Depth images from the kinect and realsense cameras.

Thanks! But I should warn that the raw performance of the network was not as good as it looks in the video, there was some very heavy filtering involved using also information from the game that you can see in the video!

**Comment by castiel520** [comment]
@kilsenp Thanks, I'll have a try!

**Comment by anguszxd** [comment]
Hello, @kilsenp I also saw your demo video on youtube, it's very interesting. I have browsen your code briefly and it seems that the loss you used here is different from original paper. I'm not sure whether it is my mistake. The original paper uses ctc_loss, but yours are not. It makes me a bit confused ...

**Comment by kilianyp** [comment]
Hi,
thank you for your interest.
It's used here:
https://github.com/kilsenp/R3DCNN-tensorflow/blob/master/networks/r3dcnn.py#L151

Best regards

**Comment by anguszxd** [comment]
@kilsenp Thanks!

**Comment by buaa-luzhi** [comment]
@castiel520 @anguszxd
Hello, can you tell me the website of the video. Thanks  so much.

**Comment by kilianyp** [comment]
Here is the video to the project [Gestamemory](https://www.youtube.com/watch?v=RUxZ75z3SgA) I used it in.
